name: observatory
description: Game price tracker.
publish_to: "none"
version: 1.4.4

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  app_links: ^6.2.0
  awesome_flutter_extensions: ^1.3.0
  awesome_notifications: ^0.10.0
  cached_network_image: ^3.4.0
  chewie: ^1.8.5
  collection: ^1.18.0
  country_picker: ^2.0.26

  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  easy_refresh: ^3.4.0
  fl_chart: ^0.70.0
  flex_color_scheme: ^8.0.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  flutter_slidable: ^4.0.0
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  go_router: ^14.2.6
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  hooks_riverpod: ^2.5.2
  html_unescape: ^2.0.0
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  lzstring: ^2.0.0+2
  oauth2: ^2.0.3
  photo_view: ^0.15.0
  purchases_flutter: ^8.2.1
  sentry_flutter: ^8.9.0
  share_plus: ^10.0.0
  sliver_tools: ^0.2.12
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  video_player: ^2.9.2
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: b783000
  youtube_player_flutter: ^9.1.1

flutter_launcher_icons:
  android:
    generate: true
    background_color: "#FFFFFF"
  ios:
    generate: true
    background_color: "#FFFFFF"
  image_path_android: "assets/icon/observatory.png"
  image_path_ios: "assets/icon/observatory_ios.png"

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint:
  dart_code_metrics_presets: ^2.17.0
  emulators: ^0.6.1
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  lints: ^5.0.0
  mockito: ^5.4.4
  riverpod_lint:
  sentry_dart_plugin: ^2.1.0
  test:

sentry:
  ignore_missing: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/observatory.png
    - assets/images/bmc-button.png
    - assets/images/itad-logo.jpg
    - secrets.env
    - secrets.dev.env
    - assets/google_fonts/
