const List<String> steamTags = [
  '1980s',
  '1990\'s',
  '2.5D',
  '2D Fighter',
  '2D Platformer',
  '2D',
  '360 Video',
  '3D Fighter',
  '3D Platformer',
  '3D Vision',
  '3D',
  '4 Player Local',
  '4X',
  '6DOF',
  'Abstract',
  'Action Roguelike',
  'Action RPG',
  'Action-Adventure',
  'Action',
  'Addictive',
  'Adventure',
  'Agriculture',
  'Aliens',
  'Alternate History',
  'America',
  'Animation & Modeling',
  'Anime',
  'Arcade',
  'Archery',
  'Arena Shooter',
  'Artificial Intelligence',
  'Assassin',
  'Asymmetric VR',
  'Asynchronous Multiplayer',
  'Atmospheric',
  'ATV',
  'Audio Production',
  'Auto Battler',
  'Automation',
  'Automobile Sim',
  'Base Building',
  'Base Building',
  'Baseball',
  'Based on a Novel',
  'Basketball',
  'Batman',
  'Battle Royale',
  'Beat \'em up',
  'Beautiful',
  'Benchmark',
  'Bikes',
  'Blood',
  'BMX',
  'Board Game',
  'Bowling',
  'Boxing',
  'Building',
  'Building',
  'Bullet Hell',
  'Bullet Time',
  'Capitalism',
  'Card Battler',
  'Card Game',
  'Cartoon',
  'Cartoony',
  'Casual',
  'Cats',
  'Character Action Game',
  'Character Customization',
  'Chess',
  'Choices Matter',
  'Choose Your Own Adventure',
  'Cinematic',
  'City Builder',
  'Class-Based',
  'Classic',
  'Clicker',
  'Co-op Campaign',
  'Co-op',
  'Cold War',
  'Collectathon',
  'Colony Sim',
  'Colorful',
  'Combat Racing',
  'Combat',
  'Comedy',
  'Comic Book',
  'Comic Book',
  'Competitive',
  'Conspiracy',
  'Controller',
  'Conversation',
  'Crafting',
  'Crime',
  'Crowdfunded',
  'CRPG',
  'Cult Classic',
  'Cute',
  'Cyberpunk',
  'Cycling',
  'Dark Comedy',
  'Dark Fantasy',
  'Dark',
  'Dating Sim',
  'Deckbuilding',
  'Demons',
  'Design & Illustration',
  'Destruction',
  'Detective',
  'Difficult',
  'Dinosaurs',
  'Diplomacy',
  'Diplomacy',
  'Documentary',
  'Dog',
  'Dragons',
  'Drama',
  'Driving',
  'Dungeon Crawler',
  'Dungeons & Dragons',
  'Dynamic Narration',
  'Early Access',
  'Economy',
  'Education',
  'Education',
  'Emotional',
  'Epic',
  'Episodic',
  'eSports',
  'Experience',
  'Experimental',
  'Experimental',
  'Exploration',
  'Faith',
  'Family Friendly',
  'Fantasy',
  'Farming Sim',
  'Fast-Paced',
  'Feature Film',
  'Female Protagonist',
  'Fighting',
  'First-Person',
  'Fishing',
  'Flight',
  'Flight',
  'FMV',
  'FMV',
  'Football',
  'Foreign',
  'FPS',
  'Free to Play',
  'Funny',
  'Futuristic',
  'Gambling',
  'Game Development',
  'GameMaker',
  'Games Workshop',
  'Gaming',
  'God Game',
  'Golf',
  'Gore',
  'Gothic',
  'Grand Strategy',
  'Great Soundtrack',
  'Grid-Based Movement',
  'Gun Customization',
  'Hack and Slash',
  'Hack and Slash',
  'Hacking',
  'Hacking',
  'Hand-drawn',
  'Hardware',
  'Heist',
  'Heist',
  'Hero Shooter',
  'Hex Grid',
  'Hidden Object',
  'Historical',
  'Hockey',
  'Horror',
  'Horses',
  'Hunting',
  'Idler',
  'Illuminati',
  'Immersive Sim',
  'Indie',
  'Intentionally Awkward Controls',
  'Interactive Fiction',
  'Inventory Management',
  'Investigation',
  'Investigation',
  'Isometric',
  'Jet',
  'JRPG',
  'Kickstarter',
  'Lara Croft',
  'LEGO',
  'Lemmings',
  'Level Editor',
  'LGBTQ+',
  'Life Sim',
  'Linear',
  'Local Co-Op',
  'Local Multiplayer',
  'Logic',
  'Loot',
  'Looter Shooter',
  'Lore-Rich',
  'Lovecraftian',
  'Magic',
  'Management',
  'Management',
  'Mars',
  'Martial Arts',
  'Massively Multiplayer',
  'Masterpiece',
  'Match 3',
  'Mature',
  'Mechs',
  'Medical Sim',
  'Medieval',
  'Memes',
  'Metroidvania',
  'Military',
  'Mini Golf',
  'Minigames',
  'Minimalist',
  'Mining',
  'Mining',
  'MMORPG',
  'MOBA',
  'Mod',
  'Moddable',
  'Modern',
  'Motocross',
  'Motorbike',
  'Mouse only',
  'Movie',
  'Multiplayer',
  'Multiple Endings',
  'Music-Based Procedural Generation',
  'Music',
  'Mystery Dungeon',
  'Mystery',
  'Mythology',
  'Narration',
  'Nature',
  'Naval Combat',
  'Naval',
  'Ninja',
  'Noir',
  'Nonlinear',
  'NSFW',
  'Nudity',
  'Offroad',
  'Old School',
  'On-Rails Shooter',
  'Online Co-Op',
  'Open World Survival Craft',
  'Open World',
  'Open World',
  'Otome',
  'Outbreak Sim',
  'Parkour',
  'Party-Based RPG',
  'Perma Death',
  'Philosophical',
  'Photo Editing',
  'Physics',
  'Pinball',
  'Pirates',
  'Pixel Graphics',
  'Platformer',
  'Point & Click',
  'Political Sim',
  'Political',
  'Politics',
  'Pool',
  'Post-apocalyptic',
  'Precision Platformer',
  'Procedural Generation',
  'Programming',
  'Programming',
  'Psychedelic',
  'Psychological',
  'Puzzle',
  'PvE',
  'PvP',
  'Quick-Time Events',
  'Racing',
  'Real Time Tactics',
  'Real-Time with Pause',
  'Real-Time',
  'Realistic',
  'Relaxing',
  'Remake',
  'Replay Value',
  'Resource Management',
  'Retro',
  'Rhythm',
  'Robots',
  'Roguelike',
  'Roguelite',
  'Roguevania',
  'Romance',
  'Rome',
  'RPG',
  'RPGMaker',
  'RTS',
  'Runner',
  'Sailing',
  'Sandbox',
  'Satire',
  'Sci-fi',
  'Science',
  'Score Attack',
  'Sequel',
  'Sexual Content',
  'Shoot \'Em Up',
  'Shooter',
  'Short',
  'Side Scroller',
  'Silent Protagonist',
  'Simulation',
  'Singleplayer',
  'Skateboarding',
  'Skating',
  'Skiing',
  'Sniper',
  'Snow',
  'Snowboarding',
  'Soccer',
  'Software Training',
  'Software',
  'Sokoban',
  'Solitaire',
  'Souls-like',
  'Soundtrack',
  'Space Sim',
  'Space',
  'Spectacle fighter',
  'Spelling',
  'Split Screen',
  'Sports',
  'Star Wars',
  'Stealth',
  'Stealth',
  'Stealth',
  'Steam Machine',
  'Steampunk',
  'Story Rich',
  'Strategy RPG',
  'Strategy',
  'Stylized',
  'Submarine',
  'Superhero',
  'Supernatural',
  'Surreal',
  'Survival Horror',
  'Survival',
  'Survival',
  'Swordplay',
  'Tabletop',
  'Tabletop',
  'Tactical RPG',
  'Tactical',
  'Tanks',
  'Team-Based',
  'Tennis',
  'Text-Based',
  'Text-Based',
  'Third Person',
  'Third-Person Shooter',
  'Thriller',
  'Time Attack',
  'Time Management',
  'Time Manipulation',
  'Time Travel',
  'Top-Down Shooter',
  'Top-Down',
  'Touch-Friendly',
  'Tower Defense',
  'TrackIR',
  'Trading Card Game',
  'Trading',
  'Trading',
  'Traditional Roguelike',
  'Trains',
  'Transhumanism',
  'Transportation',
  'Trivia',
  'Turn-Based Combat',
  'Turn-Based Strategy',
  'Turn-Based Tactics',
  'Turn-Based Tactics',
  'Turn-Based',
  'Tutorial',
  'Twin Stick Shooter',
  'Typing',
  'Underground',
  'Underwater',
  'Unforgiving',
  'Utilities',
  'Vampire',
  'Vehicular Combat',
  'Video Production',
  'Villain Protagonist',
  'Violent',
  'Visual Novel',
  'Voice Control',
  'Voxel',
  'VR',
  'Walking Simulator',
  'War',
  'Wargame',
  'Warhammer 40K',
  'Web Publishing',
  'Werewolves',
  'Western',
  'Word Game',
  'World War I',
  'World War II',
  'Wrestling',
];
